services:

  simple-store:
    container_name: simple-object-store
    #image: sedrad/simplestore:latest
    build:
      context: ./SimpleStore
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - '5000:80'

  simple-store-ui:
    container_name: simple-store-admin
    #image: sedrad/simplestore-admin:latest
    depends_on:
      - simple-store
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
    build:
      context: ./SimpleStore.Admin
      dockerfile: Dockerfile
    environment:
      - API__Endpoint=${API_ENDPOINT}
      - API__Key=${API_KEY}
      - OpenId__Authority=${OPENID_AUTHORITY}
      - OpenId__ClientId=${OPENID_CLIENT_ID}
      - OpenId__ClientSecret=${OPENID_CLIENT_SECRET}
      - DisableHttpsMetadata=true
    ports:
      - '5001:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"